# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: pt-BR
tone_instructions: Você deve falar como o Sr. T. Tenho pena do tolo que não fala assim!
early_access: true
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: ' @coderabbitai summary'
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: ' @coderabbitai'
  auto_title_instructions: 'Crie um título descritivo e conciso em português brasileiro'
  review_status: true
  commit_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  poem: true
  labeling_instructions: 
    - label: 'documentation'
      description: 'Para mudanças na documentação'
    - label: 'enhancement' 
      description: 'Para melhorias e novas funcionalidades'
    - label: 'bug'
      description: 'Para correção de bugs'
    - label: 'performance'
      description: 'Para otimizações de performance'
    - label: 'security'
      description: 'Para correções de segurança'
    - label: 'refactor'
      description: 'Para refatoração de código'
  path_filters: []
  path_instructions:
    - path: 'docs/**'
      instructions: 'Foque na clareza da documentação, ortografia e estrutura em português brasileiro'
    - path: 'blog/**'
      instructions: 'Revise gramática, estilo e SEO dos posts em português brasileiro'
    - path: 'src/**'
      instructions: 'Analise performance, acessibilidade e melhores práticas React'
    - path: '*.json'
      instructions: 'Valide estrutura JSON e configurações'
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: ['WIP', 'Draft', 'Rascunho']
    labels: ['needs-review']
    drafts: true
    base_branches: ['main', 'master', 'develop']
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: error
      threshold: 90
    title:
      mode: error
      requirements: 'Título deve ser descritivo e em português brasileiro'
    description:
      mode: error
    issue_assessment:
      mode: error
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    phpmd:
      enabled: true
    phpcs:
      enabled: true
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    flake8:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    clippy:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    pylint:
      enabled: true
    oxc:
      enabled: true
    shopifyThemeCheck:
      enabled: true
    luacheck:
      enabled: true
    brakeman:
      enabled: true
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: true
    checkmake:
      enabled: true
chat:
  auto_reply: true
  integrations:
    jira:
      usage: enabled
    linear:
      usage: enabled
    slack:
      enabled: true
    discord:
      enabled: true
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: ['**/*.md', '**/*.mdx', '**/*.js', '**/*.ts', '**/*.jsx', '**/*.tsx', '**/*.json', '**/*.yaml', '**/*.yml']
  learnings:
    scope: global
  issues:
    scope: global
  jira:
    usage: enabled
    project_keys: []
  linear:
    usage: enabled
    team_keys: []
  pull_requests:
    scope: global
code_generation:
  docstrings:
    language: pt-BR
    path_instructions:
      - path: 'src/**'
        instructions: 'Gere documentação em português brasileiro para componentes React'
      - path: 'docs/**'
        instructions: 'Mantenha consistência com o estilo da documentação existente'
  unit_tests:
    enabled: true
    path_instructions:
      - path: 'src/**'
        instructions: 'Crie testes unitários para componentes React usando Jest'
      - path: '**/*.js'
        instructions: 'Gere testes para funções utilitárias'
annotations:
  enabled: true
  threshold: info
  coverage_threshold: 80
integrations:
  github:
    enabled: true
    auto_merge:
      enabled: true
      conditions:
        - reviews_required: 1
        - status_checks_passed: true
        - no_conflicts: true
    branch_protection:
      enabled: true
      require_reviews: true
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
  webhooks:
    enabled: true
    events: ['pull_request', 'push', 'issues', 'pull_request_review']
notifications:
  email:
    enabled: true
    events: ['review_completed', 'security_issues', 'critical_errors']
  slack:
    enabled: true
    webhook_url: ''
    channels: ['#dev', '#code-review']
workflow:
  auto_merge:
    enabled: true
    strategy: squash
    delete_branch: true
    require_all_checks: true
  auto_fix:
    enabled: true
    safe_changes_only: true
    categories: ['formatting', 'imports', 'unused_variables']